parse_git_branch() {
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "

alias pu="vendor/bin/phpunit"
alias puf="vendor/bin/phpunit --filter"
alias putu="vendor/bin/phpunit --testsuite Unit"
alias putf="vendor/bin/phpunit --testsuite Feature"
