parse_git_branch() {
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "

alias gf="git flow "
# laravel related 
alias pa="php artisan "
alias pat="php artisan test "
alias pao="php artisan optimize "
alias pam="php artisan migrate:fresh --seed "
alias lumen="composer create-project --prefer-dist laravel/lumen "
#symfony related
alias pc="php bin/console "
# phpunit related
alias pu="vendor/bin/phpunit "
alias puf="vendor/bin/phpunit --filter " 
alias putu="vendor/bin/phpunit --testsuite Unit "
alias putf="vendor/bin/phpunit --testsuite Feature "

