

# laravel related 
alias pac="php artisan cache:clear && php artisan config:cache && php artisan view:cache && php artisan route:cache" 
alias pa="php artisan "
alias pat="php artisan test "
alias pao="php artisan optimize "
alias pam="php artisan migrate:fresh --seed "
alias lumen="composer create-project --prefer-dist laravel/lumen "
alias sail='[ -f sail ] && sh sail || sh ./vendor/bin/sail'
#symfony related
alias pc="php bin/console "
# phpunit related
alias pu="vendor/bin/phpunit "
alias puf="vendor/bin/phpunit --filter " 
alias putu="vendor/bin/phpunit --testsuite Unit "
alias putf="vendor/bin/phpunit --testsuite Feature "

# git related
alias gf="git fetch "
alias gs="git status "
alias gd="git diff "
alias gdc="git diff --cached "
alias gb="git branch "
alias gc="git commit "
alias gca="git commit -a "
alias gcam="git commit -am "
alias gco="git checkout "
alias gcb="git checkout -b "
alias gcp="git cherry-pick "
alias gpl="git pull "
alias gplm="git pull origin master "
alias gps="git push "
alias gpsa="git push --all "
alias gpsu="git push --tags "
alias gpsb="git push --branch "
alias gr="git remote -v "
alias gra="git remote add "
alias grr="git remote rm "
alias gcl="git clone "
alias gclb="git clone --branch "
alias gclo="git clone --origin "
alias gclob="git clone --origin --branch "
