call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-fugitive'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'scrooloose/nerdtree'
"Plug 'scrooloose/nerdcommenter'
Plug 'wakatime/vim-wakatime'
"Plug 'christoomey/vim-tmux-navigator'
Plug 'google/vim-maktaba'
Plug 'google/vim-codefmt'
" Also add Glaive, which is used to configure codefmt's maktaba flags. See
" `:help :Glaive` for usage.
Plug 'google/vim-glaive'
" color schemes
Plug 'morhetz/gruvbox'
"Plug 'phpactor/phpactor'
"Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }
"Plug 'airblade/vim-gitgutter'
"Plug 'editorconfig/editorconfig-vim'

"Plug 'tpope/vim-eunuch'
"Plug 'w0rp/ale'
"Plug 'tpope/vim-surround'
"Plug 'jiangmiao/auto-pairs'
" Plug 'valloric/youcompleteme'


" plugins from youtube

" Specify a directory for plugins

"Plug 'Xuyuanp/nerdtree-git-plugin'
"Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
"Plug 'ryanoasis/vim-devicons'
"Plug 'airblade/vim-gitgutter'
"Plug 'prettier/vim-prettier', { 'do': 'yarn install' }

call plug#end()


source ~/.vim/vim.conf/custom.vimrc
source ~/.vim/vim.conf/coc.vimrc
source ~/.vim/vim.conf/nerdtree.vimrc
source ~/.vim/vim.conf/prettier.vimrc
source ~/.vim/vim.conf/lightline.vimrc
"source ~/.vim/vim.conf/codefmt.vimrc
source ~/.vim/vim.conf/nerdcommenter.vimrc

